### PR TITLE
Heroku deployment button

### LINKED ISSUE #1: Deploy to heroku
I think that we need a easy way(deploy button?) to deploy this app to heroku platform.

### PR DESCRIPTION
**Pull request by sgerrand**
💁  This change adds a "Deploy with Heroku" button.

Closes #1

### CODE REVIEW

**Comment by sgerrand** [comment]
👋  @raelmax: Would you please review this change.

**Comment by raelmax** [comment]
Hey @sgerrand, thank you for your contribution!

But I think that we need a more complex change to put this project working on heroku. When I click to the button, i'm redirected to heroku site but I received a error on building step.

I think we need follow this approach:
- Configure the build steps by changing dockerfile and makefile, like the heroku example project do: https://github.com/heroku/go-getting-started

**Comment by sgerrand** [comment]
@raelmax: Done! Note that I've used govendor to handle your dependencies. Have a look at `vendor/vendor.json` in this changeset.

You can test the button by using https://heroku.com/deploy?template=https://github.com/sgerrand/city/tree/heroku-deploy-button. This will simulate the behaviour once these changes are merged in.

**Review by raelmax — APPROVED** [review]
Great, @sgerrand! I've tried deploy to heroku but the application was returning a error. But I think it is a problem on my Procfile. I will merge your code and fix this.

Thanks! :)

**Pull request merged**
